source 'https://rubygems.org'

gem 'rails', '3.2.16'
gem 'mongoid', '3.1.6'
gem 'kaminari', '0.15.1'
gem "mongo_session_store-rails3", '5.0.1'

gem 'jquery-rails'
gem 'bootstrap-sass', '3.1.1.1'
gem 'kaminari-bootstrap', '3.0.1'
gem 'momentjs-rails', '~> 2.5.0'
gem 'bootstrap3-datetimepicker-rails', '~> 3.0.0'
gem 'bxslider-rails', '4.1.0'

gem 'debugger', group: [:development, :test]

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'



# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', :platforms => :ruby

  gem 'uglifier', '>= 1.0.3'
end



# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'debugger'
